 
name: flutter_godot_plugin 
description: A Flutter plugin to integrate Godot games into Flutter apps for iOS. 
version: 0.0.1 
 
environment: 
  sdk: ">=2.12.0 <3.0.0" 
  flutter: ">=1.20.0" 
 
dependencies: 
  flutter: 
    sdk: flutter 
 
flutter: 
  plugin: 
    platforms: 
      ios: 
        pluginClass: SwiftFlutterGodotPlugin 
